### PR TITLE
Add additional dsdl path for loading

### PR DESCRIPTION
**Pull request by marcojob**
Add additional DSDL path for loading correctly in PX4-Autopilot, this should fix the issue dronecan/libuavcan#3

### CODE REVIEW

**Comment by potaito** [comment]
I too ran into the issue you mentioned when trying to compile PX4. I can confirm that this fix works with the following parameters:

- Checked out most master of https://github.com/dronecan/libuavcan, which is this commit as of today: https://github.com/dronecan/libuavcan/commit/5eec0220302dfaa23602d7ee901cde0579fbf9e2
- Checked out your branch
- Running Ubuntu 22.04

Since you are just adding yet another search path to the list, I don't see any harm in merging this. And thanks for saving me some time :)

**Comment by potaito** [comment]
@tridge merge? :smile:

**Comment by aentinger** [comment]
This resolves the issue described [here](https://github.com/dronecan/libuavcan/issues/3) also for me. Please merge and update libuavcan :+1:

**Review by tridge — APPROVED** [review]

**Comment by potaito** [comment]
Thank you kind sir!!!

**Pull request merged**
